language: java
sudo: false # faster builds

cache:
  directories:
  - $HOME/.m2

jdk:
  - oraclejdk7
  - oraclejdk8
  - openjdk7
  - openjdk8

install: true

script:
  - mvn cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)